### ISSUE TITLE
Actual North direction and what showing in app is different .

### ISSUE THREAD

**Issue by shahparth99999** [iutinvg/compass#11]
Compass is not showing correct North direction. Every time it points to the different north direction which is not correct. 
I open my device in any direction it should show north in the right direction.
Can you help me on this, I want to show my compass to always in the north direction, on correct north direction.

**Comment by iutinvg** [comment]
What device have you tried? I suggest trying another device to see if it behaves the same. Also, the sensors can (though not always) really go creasy near certain objects and inside the buildings.

So, your problem looks like related to hardware, try to ensure it's not the matter. Then go further.

**Comment by shahparth99999** [comment]
> What device have you tried? I suggest trying another device to see if it behaves the same. Also, the sensors can (though not always) really go creasy near certain objects and inside the buildings.
> 
> So, your problem looks like related to hardware, try to ensure it's not the matter. Then go further.

I have tried in Pixel 2 XL device. But it's not working. In which device you have tested and it's working?

**Comment by iutinvg** [comment]
Different: Alcatel, Samsung, LG, etc. Just try some other devices. Also, ensure it works the same way outside. It easily may be something fusing in the place you launch the app.
