### ISSUE TITLE
Hope to express the direction in string

### ISSUE THREAD

**Issue by kirilldev1010** [iutinvg/compass#12]
if (348.75 <= bearing && bearing <= 360) {
            return "N";
        } else if (0 <= bearing && bearing <= 11.25) {
            return "N";
        } else if (11.25 < bearing && bearing <= 33.75) {
            return "NNE";
        } else if (33.75 < bearing && bearing <= 56.25) {
            return "NE";
        } else if (56.25 < bearing && bearing <= 78.75) {
            return "ENE";
        } else if (78.75 < bearing && bearing <= 101.25) {
            return "E";
        } else if (101.25 < bearing && bearing <= 123.75) {
            return "ESE";
        } else if (123.75 < bearing && bearing <= 146.25) {
            return "SE";
        } else if (146.25 < bearing && bearing <= 168.75) {
            return "SSE";
        } else if (168.75 < bearing && bearing <= 191.25) {
            return "S";
        } else if (191.25 < bearing && bearing <= 213.75) {
            return "SSW";
        } else if (213.75 < bearing && bearing <= 236.25) {
            return "SW";
        } else if (236.25 < bearing && bearing <= 258.75) {
            return "WSW";
        } else if (258.75 < bearing && bearing <= 281.25) {
            return "W";
        } else if (281.25 < bearing && bearing <= 303.75) {
            return "WNW";
        } else if (303.75 < bearing && bearing <= 326.25) {
            return "NW";
        } else if (326.25 < bearing && bearing < 348.75) {
            return "NNW";
        } else {
            return "";
        }

**Comment by iutinvg** [comment]
I've decided to use a way which looks trickier, but (I hope) won't drain the device's battery as much: binary search. 

https://github.com/iutinvg/compass/blob/master/app/src/main/java/com/sevencrayons/compass/SOTWFormatter.java

But thank you. I like the direct approach, in most this is exactly what is needed.
