### ISSUE TITLE
compilation bug

### ISSUE THREAD

**Issue by francoisnicolas** [iutinvg/compass#13]
Hello,

I have this compilation error : 
ERROR: This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.

I have the latest version of Android Studio.
You should re-install your Android Studio, and test your software with it before publishing it on github

**Comment by iutinvg** [comment]
Hello,

I can not reproduce the problem. I have cloned a fresh copy and followed the instruction https://github.com/iutinvg/compass#how-to-build

Could you provide more details? Maybe you open a wrong folder in the Android Studio?

Thanks.

**Comment by francoisnicolas** [comment]
Hello,

Perhaps, I have made a mistake. In fact, I have Android Studio 3.4.2
The version is not very old, so many developers can't open your project.

I have found another project :  https://github.com/AlexandreLouisnard/android-compass   which work well for me .


[https://avatars3.githubusercontent.com/u/16859084?s=400&v=4]<https://github.com/AlexandreLouisnard/android-compass>
GitHub - AlexandreLouisnard/android-compass: A compass implementation for Android, using the magnetic and accelerometer device sensors to show the magnetic North on a circle.<https://github.com/AlexandreLouisnard/android-compass>
Android Compass. Author: Alexandre Louisnard alouisnard@gmail.com Android Java Application 2017. DESCRIPTION. Compass implementation providing azimuth (East of the magnetic North, counterclockwise), pitch (vertical inclination) and roll (horizontal inclination) of the device, in degrees.
github.com

If the problem does not come from the version of Android Studio, perhaps, you have modified the configuration of your android studio, and users haven't the same.
Thank you for your work.



________________________________
De : Viacheslav Iutin <notifications@github.com>
Envoyé : vendredi 1 novembre 2019 14:42
À : iutinvg/compass <compass@noreply.github.com>
Cc : francoisnicolas <francoisnicolas@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [iutinvg/compass] compilation bug (#13)


Hello,

I can not reproduce the problem. I have cloned a fresh copy and followed the instruction https://github.com/iutinvg/compass#how-to-build

Could you provide more details? Maybe you open a wrong folder in the Android Studio?

Thanks.

**Comment by iutinvg** [comment]
Hi,

I've decided to reinstall Android Studio and followed this very useful suggestion https://stackoverflow.com/a/18458893/444966 

Then I have installed Android Studio again and cloned a fresh copy of the project. When I opened it in the IDE the only problem was to install SDK version 28 (29 is installed by default on the first start).

Once it's done the project is built OK.

Any ideas?

Thanks.

**Comment by francoisnicolas** [comment]
Hi,

No I haven't any idea.
I have installed it on a PC (not a mac), and I don't have github.
It's not the latest version of Android Studio.

Don't spend too much time on this trouble. Perhaps it's my configuration that is not good.

Thanks.
________________________________
De : Viacheslav Iutin <notifications@github.com>
Envoyé : samedi 2 novembre 2019 07:40
À : iutinvg/compass <compass@noreply.github.com>
Cc : francoisnicolas <francoisnicolas@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [iutinvg/compass] compilation bug (#13)


Hi,

I've decided to reinstall Android Studio and followed this very useful suggestion https://stackoverflow.com/a/18458893/444966

Then I have installed Android Studio again and cloned a fresh copy of the project. When I opened it in the IDE the only problem was to install SDK version 28 (29 is installed by default on the first start).

Once it's done the project is built OK.

Any ideas?

Thanks.
